FROM golang:1.25.4-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /mockserver ./cmd/mockserver

FROM alpine:3.20

RUN apk add --no-cache ca-certificates tzdata

COPY --from=build /mockserver /mockserver

EXPOSE 9999

ENTRYPOINT ["/mockserver"]
